### ISSUE TITLE
For some streams Team/Community Guidance is not visible on the website

### ISSUE THREAD

**Issue by DRaichev** [owaspsamm/website#158]
You get "There's no guidance for this Stream, yet. Be the first to provide Community guidance!" even when community guidance is available for the stream in question.

Example:
https://owaspsamm.org/model/governance/strategy-and-metrics/stream-b/
Here it shows no guidance is available, but
https://docs.google.com/spreadsheets/d/1qkWd516YYjnw84gOJEZ_azL0UZWgsM0tsV5d6XluvRM/edit#gid=0
here row 47 & 48 are community guidance for that stream and row 69 is team guidance for that stream

**Comment by Pat-Duarte** [comment]
Adding documents to the stream guidance on the website is a manual process. We need to improve that process.
For now, when someone approves guidance for a stream that has no content on the website, they need to create an issue to add that content.

We have an issue #159 for the Team Guidance but I need to talk to the team about the Community guidance you're mentioning. Thanks for bringing it up.

**Comment by Pat-Duarte** [comment]
There was also a saved filter view in the spreadsheet you mentioned that seems to have been deleted...

**Comment by DRaichev** [comment]
Yeah I figured out how it works and I will submit a pr with a fix soon.
