### ISSUE TITLE
Update the Assessments Page to point to the SAMM Assessment 2.0.6 Google Sheets

### ISSUE THREAD

**Issue by infosecdad** [owaspsamm/website#28]
Update the link to the Google Sheets Assessment link to point to the 2.0.6 version of the Google Sheets as Google doesn't like to allow stomping the same file for versioning.

https://docs.google.com/spreadsheets/d/1a8aH4_nwZq9M_5_t_tX8DGpblivKdzQcwU_T6t8OEYQ/view

Also, please remove the reference to the ConcordUSA tool as it is not actively maintained or reflective of the current SAMM.
Can add references to SAMMY and Sammwise if appropriate.

**Comment by infosecdad** [comment]
Sorry, not sure what happened in the google drive folder, but that file on the link above somehow became the old 2.0.3 again.  The correct link to 2.0.6 is https://docs.google.com/spreadsheets/d/1jmLVltRhuG19AX5cLUcWH1Qox2Uic17rD29gMVG5zDE/view

Thanks!

**Comment by infosecdad** [comment]
Created Pull Request #33 for the change.

**Comment by Pat-Duarte** [comment]
https://github.com/owaspsamm/website/pull/33
This was merged. Closing the issue now.
