### ISSUE TITLE
Publish Practitioner blog

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/website#50]
Create a blog to announce the SAMM Practitioners

**Comment by Pat-Duarte** [comment]
@SebaDele please take a look at this document
https://docs.google.com/document/d/1CrKtVxo6p7n04RIYQbxl0JdQAmYHpUdiO7L324C44nY/edit?usp=sharing

**Comment by Pat-Duarte** [comment]
Practitioners' page has the relevant content. No need for blog post.
