### ISSUE TITLE
SAMM website generation issue

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/website#51]

**Comment by Pat-Duarte** [comment]
https://docs.google.com/document/d/1VNlGm12cxRyxlv0XqM-YagCLIj5QXivmY9dQo_a4EoQ/edit

**Comment by aramhovsepyan** [comment]
Codific will be fixing this issue as a donation to the project. How can we add Alex from my team (https://github.com/BackNot) to the list of assignees?

**Comment by SebaDele** [comment]
Added https://github.com/BackNot as member, once he accepts I can assign him to this issue (FYI  @aramhovsepyan )

**Comment by BackNot** [comment]
I believe that the issue will be resolved after the following things:

Two core repository issues - 
1. https://github.com/owaspsamm/core/issues/155 
2.https://github.com/owaspsamm/core/issues/158

Pull request to this repository -
https://github.com/owaspsamm/website/pull/245

I am going to briefly summarize the process for the sake of clarity and documentation -

1. When a new tag is created to the core repository markdown files are generated there (from the yaml files by using https://github.com/owaspsamm/process-yaml-content) and pushed to branch "markdown/v{version}". Then a "repository dispatch" event is made to this repository with the new version passed as payload.

2. When the signal is received this repository will update its hugo modules dependencies by using the "markdown" branch from the core repository. After that the deploy job will run and the new files will be pushed to branch "gh-pages".

**Comment by aramhovsepyan** [comment]
this is now resolved. I have released a pre-release version 2.0.11. We are ready for 2.1.0 release.
