### ISSUE TITLE
SAMM Guidance - create MVP with GDocs and forms - linked from the website

### ISSUE THREAD

**Issue by SebaDele** [owaspsamm/website#54]
Add guidance in many forms (mappings, projects, references, tools, best practices, ...) to the SAMM activities.
We bootstrap this with an MVP using Google Docs and Forms to insert/update the SAMM Guidance.

In this MVP we will bootstrap 30 Guidance Docs (one per SAMM Stream).
Each of these Guidance Docs will be linked form the Model pages on the website.

**Comment by SebaDele** [comment]
- [ ] write text that explains the guidance @SebaDele 
      - What’s this document?
      - How to contribute
      - Categories
      - Tags

- [ ] Have links to guidance doc from activity pages on the website @Pat-Duarte

**Comment by Pat-Duarte** [comment]
@SebaDele 
There's a **draft** version of the document explaining community guidance here:
https://docs.google.com/document/d/1Hpzpfcv1iYpO1vdMlh8dH0f945Cqb9K7NCiOy1vfJs0/edit?usp=sharing

I also created a document for definitions related to this task
https://docs.google.com/document/d/16sXX1fI78-RdXYnW6WkPiHchiGEPO3kfAWR8hRyCQG8/edit?usp=sharing

**Comment by Pat-Duarte** [comment]
**Pat**

- Done: I have the code running to display guidance. Updates [here](https://docs.google.com/document/d/16sXX1fI78-RdXYnW6WkPiHchiGEPO3kfAWR8hRyCQG8/edit?usp=sharing).
- Pending: create YAML files for all the streams with content. 

**Team (pending)**

- review of the content in the current guidance files
- have the [starting point](https://docs.google.com/document/d/1Hpzpfcv1iYpO1vdMlh8dH0f945Cqb9K7NCiOy1vfJs0/edit?usp=sharing) document ready, which I can turn into a Stream Guidance page under the Community menu.
