### ISSUE TITLE
Inconsistent color scheme on website

### ISSUE THREAD

**Issue by mtausig** [owaspsamm/website#89]
The [diagram][1] showing an overview of the model on the [about page](https://owaspsamm.org/about/) ist using a completely different color scheme then the one established previously in the (Excel or Google) spreadsheet toolbox or the [original overview diagram](https://1.bp.blogspot.com/-Mxm4FYY0C0U/XqrIwO3yw-I/AAAAAAAADEo/PGehQt9ovGgypev2SL6iIsiJVmAeNYr2gCEwYBhgL/w1200-h630-p-k-no-nu/image1.png) of SAMM v2.

I would suggest sticking to the established colours for all resources.

[1]: https://github.com/owaspsamm/website/blob/main/static/img/pages/SAMM_v2_diagram.svg

**Comment by Pat-Duarte** [comment]
The diagram on the about page is the latest version. You can also see it on the project page of the OWASP website and the SAMM PDF. 

This is a known issue for the spreadsheets but it was missing as an issue on GitHub. I created the issue in the corresponding repository: https://github.com/owaspsamm/toolbox-spreadsheet/issues/19

We hope to align them soon. Thank you for the feedback!
