### ISSUE TITLE
Links to old GitHub repository

### ISSUE THREAD

**Issue by jhschierhoelter** [owaspsamm/website#9]
In the following places I found links that still point to the old GitHub repository (https://github.com/OWASP/samm):

1. on every page - in the footer (GitHub symbol)
2. https://owaspsamm.org/assessment/ - link to spreadsheet

**Comment by jhschierhoelter** [comment]
https://owaspsamm.org/faq/
- "data files on GitHub"
-  "open Github issues"

**Comment by Pat-Duarte** [comment]
SAMM v2 release notes
http://localhost:1313/release-notes-v2/

**Comment by Pat-Duarte** [comment]
Fixed by #18 and #21
